### ISSUE TITLE
initialDBSetup fails with SyntaxError

### ISSUE THREAD

**Issue by mkrogemann** [softwerkskammer/Agora#1070]
When I follow the vagrant-related installation steps described in the README, I run into the following error:

vagrant@vagrant:/vagrant$ node softwerkskammer/initialDBSetup

/vagrant/softwerkskammer/lib/commons/misc.js:49
    return array1.length === array2.length && array1.every((v, i)=> v === arra
                                                                  ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at get (/vagrant/node_modules/CoolBeans/lib/CoolBeans.js:36:11)
    at Object.<anonymous> (/vagrant/softwerkskammer/lib/groups/group.js:4:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

**Comment by leider** [comment]
The instructions are outdated. We now require node 4. Could you please update the config and try again?

**Comment by mkrogemann** [comment]
where exactly? I tried this:

  "engines": {
    "node": ">4.0"
  },

in package.json

then npm install, but that does not seem to do the trick.

Caveat: I'm a noobie in node, would still like to support testing/fixing Agora for the next registration run if and where I can

**Comment by leider** [comment]
Die Provisionierung der vagrant vm muss ein Node 4 bereitstellen

**Comment by NicoleRauch** [comment]
@mkrogemann : Wir haben die Vagrant VM aktualisiert, schau doch nochmal, ob Du sie jetzt bei Dir zum Laufen bringst.

**Comment by mkrogemann** [comment]
the initialDBSetup step works now. good patch 👍
