### ISSUE TITLE
mocha_istanbul:testWithDB fails on MongoDB v3.2.9

### ISSUE THREAD

**Issue by coderbyheart** [softwerkskammer/Agora#1105]
```
$ ./node_modules/.bin/grunt mocha_istanbul:testWithDB
Running "mocha_istanbul:testWithDB" (mocha_istanbul) task


  ․․․․․․․․․․․!․․․․․․․․․!!․

  21 passing (2s)
  3 failing

  1) Activity application with DB - on submit - rejects an activity if there is a race condition on save:
     Error: expected 302 "Found", got 500 "Internal Server Error"
      at Test._assertStatus (node_modules/supertest/lib/test.js:250:12)                                                                              
      at Test._assertFunction (node_modules/supertest/lib/test.js:265:11)                                                                            
      at Test.assert (node_modules/supertest/lib/test.js:153:18)                                                                                     
      at Server.assert (node_modules/supertest/lib/test.js:131:12)                                                                                   
      at emitCloseNT (net.js:1549:8)                                                                                                                 
      at _combinedTickCallback (internal/process/next_tick.js:71:11)                                                                                 
      at process._tickCallback (internal/process/next_tick.js:98:9)                                                                                  

  2) Members application with DB getMembersWithInterest does not find a member by partial matches of an interest:
     Uncaught TypeError: Cannot read property 'length' of undefined
      at Must.exports.length (node_modules/must-dist/lib/assertions.js:677:32)                                                                       
      at softwerkskammer/testWithDB/membersDB/members_queries_test.js:57:33                                                                          
      at toMemberList (softwerkskammer/lib/members/memberstore.js:9:1530)                                                                            
      at apply (node_modules/lodash/lodash.js:481:27)                                                                                                
      at wrapper (node_modules/lodash/lodash.js:5156:16)                                                                                             
      at softwerkskammer/lib/persistence/persistence.js:9:3647                                                                                       
      at handleCallback (node_modules/mongodb/lib/utils.js:96:12)                                                                                    
      at node_modules/mongodb/lib/cursor.js:855:22                                                                                                   
      at handleCallback (node_modules/mongodb-core/lib/cursor.js:156:5)                                                                              
      at node_modules/mongodb-core/lib/cursor.js:604:24                                                                                              
      at queryCallback (node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:185:20)                                                            
      at node_modules/mongodb-core/lib/connection/pool.js:428:18                                                                                     
      at _combinedTickCallback (internal/process/next_tick.js:67:7)                                                                                  
      at process._tickCallback (internal/process/next_tick.js:98:9)                                                                                  

  3) Members application with DB getMembersWithInterest does not find a member when searching case sensitive:
     Uncaught TypeError: Cannot read property 'length' of undefined
      at Must.exports.length (node_modules/must-dist/lib/assertions.js:677:32)
      at softwerkskammer/testWithDB/membersDB/members_queries_test.js:64:33
      at toMemberList (softwerkskammer/lib/members/memberstore.js:9:1530)
      at apply (node_modules/lodash/lodash.js:481:27)
      at wrapper (node_modules/lodash/lodash.js:5156:16)
      at softwerkskammer/lib/persistence/persistence.js:9:3647
      at handleCallback (node_modules/mongodb/lib/utils.js:96:12)
      at node_modules/mongodb/lib/cursor.js:855:22
      at handleCallback (node_modules/mongodb-core/lib/cursor.js:156:5)
      at node_modules/mongodb-core/lib/cursor.js:604:24
      at queryCallback (node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:185:20)
      at node_modules/mongodb-core/lib/connection/pool.js:428:18
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)



=============================================================================
Writing coverage object [/home/m/www/Agora/softwerkskammer/coverageWithDB/coverage.json]
Writing coverage reports at [/home/m/www/Agora/softwerkskammer/coverageWithDB]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 41.44% ( 896/2162 )
Branches     : 19.34% ( 175/905 )
Functions    : 26.08% ( 175/671 )
Lines        : 45.08% ( 885/1963 )
================================================================================
>> 
Warning: Task "mocha_istanbul:testWithDB" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by coderbyheart** [comment]
The actual error is 

- Batch size for getMore must be positive, but received: 0

**Comment by coderbyheart** [comment]
Node.js: v6.4.0
Mongodb version: v3.2.9
