### ISSUE TITLE
Wiki Reporter fails with error message

### ISSUE THREAD

**Issue by NicoleRauch** [softwerkskammer/Agora#1135]
After having reworked the git module so that it now properly uses async processes, the wiki reporter of Softwerkskammer sometimes bails out with an error:

[31merror[39m:  Error: spawn /bin/sh EAGAIN
   at exports._errnoException (util.js:949:11)
   at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
   at onErrorNT (internal/child_process.js:348:16)
   at _combinedTickCallback (internal/process/next_tick.js:74:11)
   at process._tickCallback (internal/process/next_tick.js:98:9)
[31merror[39m:  Error: spawn /bin/sh EAGAIN
   at exports._errnoException (util.js:949:11)
   at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
   at onErrorNT (internal/child_process.js:348:16)
   at _combinedTickCallback (internal/process/next_tick.js:74:11)
   at process._tickCallback (internal/process/next_tick.js:98:9)
no changes to report

I believe this means that the software has spawned the max allowed number of processes. The bugfix should investigate why there are so many processes being spawned in parallel, and how this can be avoided (e.g. by serializing them).

**Comment by NicoleRauch** [comment]
Have not seen this problem again since the bugfix (it occurred ~3x/week before the fix) therefore I consider this problem to be solved.
