### ISSUE TITLE
The URL of a new SoCraTes activity is not set correctly

### ISSUE THREAD

**Issue by NicoleRauch** [softwerkskammer/Agora#1149]
Instead, it is empty.

**Comment by pas2al** [comment]
After creating a new activity the response seems ok (Saving Successful. Your activity has been saved.) but the page show the following error:

`TypeError: socrates/lib/registration/views/participationinfoform.pug:116`
  `  114|                 if (!registration.isPossible)`
    `115|                   .row`
 `> 116|                   p.pull-right (i.e. in #{registration.opensIn.days} days, `#`{registration.opensIn.hours} hours, #{registration.opensIn.minutes} minutes)`
    `117| `
    `118|         script.`
    `119|           $(function () {`
`Cannot read property 'days' of undefined
    at Object.pug_interp [as participationinfoform] (eval at wrap (node_modules/pug-runtime/wrap.js:6:10), <anonymous>:2410:77)
    at eval (eval at wrap (node_modules/pug-runtime/wrap.js:6:10), <anonymous>:3304:36)
    at template (eval at wrap (node_modules/pug-runtime/wrap.js:6:10), <anonymous>:3312:78)
    at Object.exports.renderFile (node_modules/pug/lib/index.js:410:38)
    at Object.exports.renderFile (node_modules/pug/lib/index.js:400:21)
    at View.exports.__express [as engine] (node_modules/pug/lib/index.js:447:11)
    at View.render (node_modules/express/lib/view.js:126:8)
    at tryRender (node_modules/express/lib/application.js:639:10)
    at EventEmitter.render (node_modules/express/lib/application.js:591:3)
    at ServerResponse.render (node_modules/express/lib/response.js:960:7)
    at socrates/lib/registration/index.js:73:11
    at socrates/lib/eventstore/eventstoreService.js:62:5
    at getGlobalEventStoreForWriting (socrates/lib/eventstore/eventstoreService.js:33:12)
    at getReadModelWithArg (socrates/lib/eventstore/eventstoreService.js:53:3)
    at socrates/lib/eventstore/eventstoreService.js:137:14
    at getReadModelWithArg (socrates/lib/eventstore/eventstoreService.js:51:12)`

**Comment by NicoleRauch** [comment]
This should be solved by following this step of the installation guide:

Copy the config/example-socrates-server-config.json and name it config/socrates-server-config.json (don't forget to remove the comment).

**Comment by pas2al** [comment]
Ok, i will give it a try, but i remember from our last conversation that this would be not necessary.

**Comment by NicoleRauch** [comment]
It obviously is, because you get the error msg.

If I claimed that it was unnecessary, then that was an error on my side, and I'm sorry for the confusion.

**Comment by pas2al** [comment]
Ok, its fine. Can be closed ;-)

**Comment by NicoleRauch** [comment]
Excellent, thanks!
