### ISSUE TITLE
FP-Group cannot be viewed

### ISSUE THREAD

**Issue by NicoleRauch** [softwerkskammer/Agora#1277]
(and please don't try this out for fun because it crashes the site...)

When trying to open the FP Learning group, this error occurs:

```
2017-04-03 23:06:49.721558500 softwerkskammer/lib/commons/renderer.js:40
2017-04-03 23:06:49.721564500   const matches = result.match(/(.?)\[\[(.+?)\]\]([^\[]?)/g);
2017-04-03 23:06:49.721565500                         ^
2017-04-03 23:06:49.721565500 
2017-04-03 23:06:49.721566500 TypeError: Cannot read property 'match' of undefined
2017-04-03 23:06:49.721566500     at evalTags (softwerkskammer/lib/commons/renderer.js:40:25)
2017-04-03 23:06:49.721567500     at Object.secondTokentextOf (softwerkskammer/lib/commons/renderer.js:80:31)
2017-04-03 23:06:53.660573500     at new Blogpost (softwerkskammer/lib/wiki/wikiObjects.js:43:28)
2017-04-03 23:06:53.660576500     at Object.parseBlogPost (softwerkskammer/lib/wiki/wikiService.js:114:22)
2017-04-03 23:06:53.660577500     at Git.readFileFs (softwerkskammer/lib/wiki/wikiService.js:128:36)
2017-04-03 23:06:53.660579500     at tryToString (fs.js:455:3)
2017-04-03 23:06:53.660813500     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
```

The problem that triggers this error is that result is undefined, so we cannot invoke match() on it.
It might be worthwhile to cover this up, especially this is triggered through the public API of the renderer.js module.
The second question is: why is result undefined? Turns out that result contains the contents of a file that gets read in wikiService.js line 126:
```
          Git.readFileFs(path, (err1, post) => {
 ```

This function only calls `fs.readFile()` internally -- why would that function return undefined while the error is falsy?

BTW all blogposts for the FP group can be viewed in the wiki just fine.

**Comment by NicoleRauch** [comment]
OK, the problem was that some blog posts do not have an initial text -- they immediately start with an enumeration. Now they are displayed with an empty teaser text.
