### ISSUE TITLE
Don't know how to unsubscribe from the Wiki

### ISSUE THREAD

**Issue by obestwalter** [softwerkskammer/Agora#1299]
Hi,

I would like to unsubscribe from the wiki updates, but don't remember how I acutually put myself on the list. Trying through the default auth methods G+ and Github ask me for registration details and StackExchange is throwing a 500.

```
Stacktrace:

InternalOpenIDError: Failed to verify assertion at node_modules/passport-openid/lib/passport-openid/strategy.js:184:36 at node_modules/passport-openid/node_modules/openid/openid.js:962:12 at node_modules/passport-openid/node_modules/openid/openid.js:1086:16 at node_modules/passport-openid/node_modules/openid/openid.js:1140:14 at Object.openid.loadAssociation (node_modules/passport-openid/node_modules/openid/openid.js:147:5) at _checkSignatureUsingAssociation (node_modules/passport-openid/node_modules/openid/openid.js:1132:10) at _checkSignature (node_modules/passport-openid/node_modules/openid/openid.js:1122:5) at _verifyAssertionAgainstProviders (node_modules/passport-openid/node_modules/openid/openid.js:1082:12) at node_modules/passport-openid/node_modules/openid/openid.js:1047:7 at node_modules/passport-openid/node_modules/openid/openid.js:580:7 at node_modules/passport-openid/node_modules/openid/openid.js:435:11 at Request._callback (node_modules/passport-openid/node_modules/openid/openid.js:209:7) at Request.self.callback (node_modules/request/request.js:188:22) at emitTwo (events.js:106:13) at Request.emit (events.js:191:7) at Request.<anonymous> (node_modules/request/request.js:1171:10) at emitOne (events.js:96:13) at Request.emit (events.js:188:7) at IncomingMessage.<anonymous> (node_modules/request/request.js:1091:12) at IncomingMessage.g (events.js:286:16) at emitNone (events.js:91:20) at IncomingMessage.emit (events.js:185:7)
```
How can I unsusbcribe from the wiki?

**Comment by leider** [comment]
HI, I've done that for you. btw. you are registered via StackExchange
