### ISSUE TITLE
"Gelöschte" Meetup Events

### ISSUE THREAD

**Issue by anrichter** [softwerkskammer/Agora#1388]
Hi,

hab mal wieder ein Problem mit der Meetup-Integration.
Und zwar wird ein auf Meetup gelöschtes Event beim Synchronisieren in Agora nicht mit gelöscht. 

Hintergrund:
Ich habe auf Meetup eine Event-Serie mit einem allgemeingültigen Text für unsere monatlichen Treffen angelegt. Die sind einmal alle in Agora auch korrekt angelegt worden.

In Vorbereitung auf das kommende Treffen bearbeite ich den Text samt Titel und Ort im Meetup. Damit scheint das alte Event gelöscht und ein neues Event angelegt zu werden. Zumindest unterscheiden sich die Event-Ids. Auf Event mit der alten Id habe ich auch keinen Zugriff mehr. Weder über die Meetup-Webseite noch über die API.

Beim Synchronisieren von Agora, wird nun das neue Event korrekt angeleg, das bereits bestehende jedoch nicht gelöscht.
Zu sehen für den März:
* [Veraltetes Event](https://www.softwerkskammer.org/activities/meetup-qgvggpyzfbqb)
* [Aktualisiertes Event](https://www.softwerkskammer.org/activities/meetup-rktnpqyzfbqb)

Könntet ihr das veraltete Event bei der Synchroniisierung löschen? 
Und als Sahnehäubchen, wenn möglich, bereits angemeldete Teilnehmer auf das neue Event übertragen?

Vielen Dank & die besten Grüße
Andreas

**Comment by NicoleRauch** [comment]
Hi Andreas,

das klingt aber ganz schön schlimm, dass Meetup da die Event-IDs einfach ändert... :-(
Wie sollen wir denn da die Zuordnung hinbekommen?

Viele Grüße
Nicole

**Comment by NicoleRauch** [comment]
Tja, und wir scheinen nicht allein zu sein mit dem Problem: https://github.com/meetup/api/issues/122

**Comment by anrichter** [comment]
Au wei. Das Ticket ist 3 Jahre alt. 

Wenns nicht geht, kapp ich die Meetup-Verbindung wieder und pflege Events, wie vorher auch, zwei mal. So viel Aufwand ist das auch nicht im Vergleich zu dem Aufwand, den ich hier verursache.

**Comment by NicoleRauch** [comment]
> Au wei. Das Ticket ist 3 Jahre alt.

Ja :-( Spricht nicht gerade für meetup tbh...

> Wenns nicht geht, kapp ich die Meetup-Verbindung wieder und pflege Events, wie vorher auch, zwei mal.

Naja, das ist ja schon ein grundsätzliches Ding, was nicht nur Dich betrifft... :-(  Ich würde da ja gern was unternehmen, ich hab nur keine gute Idee. Denn wenn sich beim Umbenennen die ID verändert, ändert sie sich sicher auch beim Verschieben des Termins, und dann gibts einfach nichts mehr, woran man sich zum Abgleich orientieren könnte.

Falls Dir noch was einfällt zur Lösung des Problems: Gerne immer her mit Ideen :-)

**Comment by leider** [comment]
Kann man nicht 1x am Tag alle Events bei Meetup suchen und ggf. löschen, wenn sie nicht mehr da sind?

**Comment by NicoleRauch** [comment]
Dann bekommt man halt nicht die Zuordnung zu den neuen Meetup-Events hin, um

> bereits angemeldete Teilnehmer auf das neue Event übertragen

zu können. Find ich nicht so gelungen, wenn wir durch die Meetup-Anbindung die Agora quasi unbrauchbar machen, weil wir uns immer die Teilnehmer von den Events wegschießen...

**Comment by anrichter** [comment]
eine wirklich gute Idee, wie man Events matchen kann, habe ich auch nicht. Außer auf das Datum und die Uhrzeit zu achten. Aber was, wenn sie die ändert? - No idea...

Was im Moment helfen würde ist, per Hand einzelne Events löschen zu können. Wenn man zusätzlich währen dessen bereits angemeldete Benutzer an ein anderes Event "hängen" könnte, hätten wir einen manuellen "Merge" von Events. So wäre ein Bereinigen der Meetup-Misere zumindest händisch möglich.

**Comment by NicoleRauch** [comment]
Hm, löschen können sollte doch jetzt schon gehen, oder?

Das mit dem Umhängen der Teilnehmer könnte natürlich auch gehen, ich frage mich nur ob man damit nicht auch viel Verwirrung stiften kann...

**Comment by anrichter** [comment]
Habe nichts zum Löschen einer Aktivität gefunden.

**Comment by NicoleRauch** [comment]
Hm, oh ich glaube, das hab ich für Meetup-Events deaktiviert.

Also, was ich mir vorstellen kann:
- Wenn ein von Meetup gekommenes Event keinen Meetup-"Master" mehr hat und wenn keine Teilnehmer drauf sind, kann man es ja einfach löschen.
- Wenn Teilnehmer drauf sind, kann man es zu einer normal bearbeitbaren Activity machen und vielleicht auch ein "Teilnehmer auf andere Activity umbuchen" Feature einbauen

Macht das einigermaßen Sinn?

**Comment by anrichter** [comment]
Klingt für mich ok. :+1:

**Comment by anrichter** [comment]
Hi Nicole,

könntest du das Löschen von Events, auch Meetup-Events, für Administratoren aktivieren?

Ich würde gern die Meetup-Verknüpfung vorerst wieder deaktivieren. 
Wenn ich das über die Gruppeneinstellung die Meetup-URL entferne, bleiben alle bisher übernommenen Meetup-Events erhalten. Diese kann ich weder bearbeiten, noch löschen.

Viele Grüße
Andreas

**Comment by anrichter** [comment]
Was mir gerade noch aufgefallen ist:
Die von Meetup aus angelegten Events in Agora haben alle eine nicht mehr existierende Meetup-ID. Scheint also, als ob Meetup die IDs nicht erst beim Bearbeiten geändert hat, sondern bereits im Vorfeld. Wann auch immer. Strange...

Es könnten also imho Events mit nicht mehr existierendem Meetup-"Master" und ohne Anmeldungen im Agora gelöscht werden. Dann wäre die Events erstmal wieder bereinigt.

Viele Grüße
Andreas

**Comment by anrichter** [comment]
Moin,

habe gerade beim Kopieren von Meetup Events noch einen Fehler mit Call-Stack bekommen:

Error: Conflicting versions.
at collection.findOneAndUpdate (softwerkskammer/lib/persistence/persistence.js:145:35)
at result (node_modules/mongodb/lib/utils.js:410:17)
at executeCallback (node_modules/mongodb/lib/utils.js:402:9)
at handleCallback (node_modules/mongodb/lib/utils.js:128:55)
at executeCommand (node_modules/mongodb/lib/operations/collection_ops.js:558:12)
at handleCallback (node_modules/mongodb/lib/utils.js:128:55)
at db.s.topology.command (node_modules/mongodb/lib/operations/db_ops.js:516:5)
at node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:397:18
at _combinedTickCallback (internal/process/next_tick.js:131:7)
at process._tickCallback (internal/process/next_tick.js:180:9)

Vielleicht hilft das an der Stelle weiter.
