### ISSUE TITLE
Problem bei der Authentifizierung

### ISSUE THREAD

**Issue by saalij** [softwerkskammer/Agora#1394]
500
failed to obtain access token (status: 400 data: { "error": "invalid_grant", "error_description": "Malformed auth code." })

Welche Authentifizierung hast Du gewählt?
  -> G+ (eventuell liegt hier das Problem nach Abschaltung von Google Plus?)
Betriebssystem und Browser inkl. Version.
  -> Win10 + Microsoft EdgeHTML 17.17134
Datum / Uhrzeit
  -> 22.05. ~19:15
Den Stacktrace
InternalOAuthError: failed to obtain access token at node_modules/openidconnect-for-passport/lib/strategy.js:101:38 at node_modules/oauth/lib/oauth2.js:191:18 at passBackControl (node_modules/oauth/lib/oauth2.js:132:9) at IncomingMessage.<anonymous> (node_modules/oauth/lib/oauth2.js:157:7) at emitNone (events.js:111:20) at IncomingMessage.emit (events.js:208:7) at endReadableNT (_stream_readable.js:1064:12) at _combinedTickCallback (internal/process/next_tick.js:138:11) at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by NicoleRauch** [comment]
Hallo,
ich hab schon einiges versucht über diese Abschaltung herauszufinden, aber leider verstehe ich immer noch nicht genau, was die da eigentlich jetzt deaktiviert haben und was nicht... Ein Teil der Benutzer kann sich anscheinend weiter einloggen, ein anderer Teil aber nicht.

Könntest Du bitte
1. Dich per Magic Link in die SWK einloggen
2. Auf Deiner Profilseite (ganz unten) eine alternative Authentifizierungsmethode wählen
3. In Zukunft dann diese benutzen?

Danke und sorry für die Umstände!

Nicole

**Comment by saalij** [comment]
Alles klar, mache ich :-)

**Comment by frankgerhardt** [comment]
Ich habe das gleiche Problem. Und habe mich dann mit Magic Link eingeloggt. 
Das ändern der Authentifizierungsmethode hat nicht funktioniert.
Es werden Google und Passwort gelistet.
Google möchte ich löschen. Geht nicht.
Einloggen mit Passwort geht nicht.

**Comment by leider** [comment]
Bei mir geht Google noch. Allerdings nur dann, wenn ich bei Google schon angemeldet bin. Sprich: beim 2. Versuch.

**Comment by leider** [comment]
E-Mail/Passwort funktioniert bei mir. 

Kannst du detaillierter werden? - wir können gerne auch direkt mailen.
