### ISSUE TITLE
Authentifizierung per Google nicht möglich

### ISSUE THREAD

**Issue by HerrDietz** [softwerkskammer/Agora#1402]
Bei funktioniert die Authentifizierung via Google reproduzierbar nicht.

**Was wollte ich tun?**
Mich zum GDCR 2019 in Münster anmelden

**Welche URL steht in der Adressleiste?**
`https://www.softwerkskammer.org/auth/openidconnect/callback?code=4%252FsQFcM9Qv2wFliagwn-ddpyG2zqm0QccRiC_1QFGwFrAr7vWNKv_jkAbUACyUMVHK1mWVFu_NTMSJAx0k5yKnHjs&scope=email+profile+openid+https%253A%252F%252Fwww.googleapis.com%252Fauth%252Fuserinfo.email+https%253A%252F%252Fwww.googleapis.com%252Fauth%252Fuserinfo.profile&authuser=0&session_state=3d465abb15e7c30688f9573ac241d257e89fa8e3..5bbc&prompt=consent#`

**Welchen Browser verwende ich?**
Version 77.0.3865.120 (Offizieller Build) (64-Bit)

Beim Login habe ich Google ausgewählt. Nach der Auswahl des zutreffenden Accounts in der Google-Maske (in dem verwendeten Browser sind mehrere Accounts aktiv) wurde ich zurück zur Seite der Softwerkskammer geleitet. Dort wurde mir aber eine Fehlermeldung angezeigt:

```
500
failed to obtain access token (status: 400 data: { "error": "invalid_grant", "error_description": "Malformed auth code." })

Stacktrace:
InternalOAuthError: failed to obtain access token at node_modules/openidconnect-for-passport/lib/strategy.js:101:38 at node_modules/oauth/lib/oauth2.js:191:18 at passBackControl (node_modules/oauth/lib/oauth2.js:132:9) at IncomingMessage.<anonymous> (node_modules/oauth/lib/oauth2.js:157:7) at emitNone (events.js:111:20) at IncomingMessage.emit (events.js:208:7) at endReadableNT (_stream_readable.js:1064:12) at _combinedTickCallback (internal/process/next_tick.js:138:11) at process._tickCallback (internal/process/next_tick.js:180:9)
```

Der gewählte Google-Account ist ganz normal eingeloggt - Über google.de komme ich ohne weitere Authentifizierung in die Einstellungen des Accounts.

**Comment by yogan** [comment]
Hab leider das gleiche Problem. Das einzige, was ich noch an zusätzlicher Info beisteuern kann, ist, dass ich die Mail-Adresse von meinem Google-Account geändert habe. Sprich, als ich vor Ewigkeiten meinen SWK-Account angelegt habe, war die Mail noch anders, als sie jetzt ist. Vielleicht lieft es daran?

**Comment by 7130Parka** [comment]
Das gleiche Problem habe ich auch. Ohne die e-Mail Adresse geändert zu haben.
Bin über den "Anmelden"-Button im "Gast"-Menü gegangen, habe dann Google als Account ausgewählt.

Windows 10 mit Chrome Version 78.0.3904.108 (Offizieller Build) (64-Bit)
04.12.2019, ~13:30Uhr

500
failed to obtain access token (status: 400 data: { "error": "invalid_grant", "error_description": "Malformed auth code." })

Stacktrace:
InternalOAuthError: failed to obtain access token at node_modules/openidconnect-for-passport/lib/strategy.js:101:38 at node_modules/oauth/lib/oauth2.js:191:18 at passBackControl (node_modules/oauth/lib/oauth2.js:132:9) at IncomingMessage.<anonymous> (node_modules/oauth/lib/oauth2.js:157:7) at emitNone (events.js:111:20) at IncomingMessage.emit (events.js:208:7) at endReadableNT (_stream_readable.js:1064:12) at _combinedTickCallback (internal/process/next_tick.js:138:11) at process._tickCallback (internal/process/next_tick.js:180:9)




Seems to me, it is in either case one of those reasons:
https://developers.google.com/identity/protocols/OAuth2#expiration

**Comment by StefanBertels** [comment]
Hallo, vor einiger Zeit ging es noch, jetzt geht es auch bei mir nicht mehr via Google. Bei mir hat sich geändert, dass ich ein zweites Google-Konto im Browser vermerkt habe, so dass ich beim Anmelden eine Auswahl treffen muss. Das richtige Konto ist bei mir aber seit langem unverändert.

```
500
failed to obtain access token (status: 400 data: { "error": "invalid_grant", "error_description": "Malformed auth code." })

Stacktrace:
InternalOAuthError: failed to obtain access token at node_modules/openidconnect-for-passport/lib/strategy.js:101:38 at node_modules/oauth/lib/oauth2.js:191:18 at passBackControl (node_modules/oauth/lib/oauth2.js:132:9) at IncomingMessage.<anonymous> (node_modules/oauth/lib/oauth2.js:157:7) at emitNone (events.js:111:20) at IncomingMessage.emit (events.js:208:7) at endReadableNT (_stream_readable.js:1064:12) at _combinedTickCallback (internal/process/next_tick.js:138:11) at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by th-gauweiler** [comment]
Dem muss ich mich leider anschliessen.
Möchte mich einfach nur anmelden und das klappt mit dem Google-Account nicht mehr.

`500
failed to obtain access token (status: 400 data: { "error": "invalid_grant", "error_description": "Malformed auth code." })

Stacktrace:
InternalOAuthError: failed to obtain access token at node_modules/openidconnect-for-passport/lib/strategy.js:101:38 at node_modules/oauth/lib/oauth2.js:191:18 at passBackControl (node_modules/oauth/lib/oauth2.js:132:9) at IncomingMessage.<anonymous> (node_modules/oauth/lib/oauth2.js:157:7) at emitNone (events.js:111:20) at IncomingMessage.emit (events.js:208:7) at endReadableNT (_stream_readable.js:1064:12) at _combinedTickCallback (internal/process/next_tick.js:138:11) at process._tickCallback (internal/process/next_tick.js:180:9)`

**Comment by leider** [comment]
Hallo, bei mir geht es, wenn ich bei Google schon angemeldet bin. Anmeldung während der Authentifizierung scheitert. Dann nochmal Authentifizieren und es geht.
Das ist nur zur Info.

Für alle, die Probleme haben: Wenn Du Deinen bei uns registrierten Mailaccount kennst, kannst Du dorthin einen Authentifizierungslink schicken. Anschließend einen neuen Athentifizierungsprovider im Profil anlegen. - Falls Du damit Probleme haben solltest, melde Dich, wo genau die Schwierigkeit lag. Dann passen wir die Hilfe entsprechend an.

**Comment by djbrown** [comment]
Ich habe das gleiche Problem, obwohl ich bereits in Google eingeloggt bin.

**Wie bist Du auf die Login Seite gegangen?**
Gast-Menü & Direktlink zur Login Seite

**Welche Authentifizierung hast Du gewählt?**
Google

**Betriebssystem und Browser inkl. Version.**
Windows 10 Home 1903
Chrome 80.0.3987.132
Firefox 73.0.1

**Datum / Uhrzeit**
08.03.2020 12:25 Uhr

**URL**
`https://www.softwerkskammer.org/auth/openidconnect/callback?code=<CODE>&scope=email+profile+openid+https%253A%252F%252Fwww.googleapis.com%252Fauth%252Fuserinfo.email+https%253A%252F%252Fwww.googleapis.com%252Fauth%252Fuserinfo.profile&authuser=0&prompt=consent#`

**Fehler**
`500
failed to obtain access token (status: 400 data: { "error": "invalid_grant", "error_description": "Malformed auth code." })
`

**Stacktrace**
`InternalOAuthError: failed to obtain access token at node_modules/openidconnect-for-passport/lib/strategy.js:101:38 at node_modules/oauth/lib/oauth2.js:191:18 at passBackControl (node_modules/oauth/lib/oauth2.js:132:9) at IncomingMessage.<anonymous> (node_modules/oauth/lib/oauth2.js:157:7) at emitNone (events.js:111:20) at IncomingMessage.emit (events.js:208:7) at endReadableNT (_stream_readable.js:1064:12) at _combinedTickCallback (internal/process/next_tick.js:138:11) at process._tickCallback (internal/process/next_tick.js:180:9)`

**Comment by djbrown** [comment]
Scheint leider immer noch nicht behoben 😬
Außerdem bekomme ich auch bei GitHub und Stackexchange eine Fehlermeldung..
Die einzige Möglichkeit ist der Magic Link

**Comment by DavidFarago** [comment]
Geht bei mir auch nicht per Google (und auch nicht per Stackexchange).
