### ISSUE TITLE
Error 500 on Payment, while being logged on github (or not)

### ISSUE THREAD

**Issue by cyriux** [softwerkskammer/Agora#970]
I tried first without being logged on GH, then while being logged on GH, and I get the same error :

TypeError: Cannot read property 'member' of undefined
    at app.post.subscriber (socrates/lib/payment/index.js:53:26)
    at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:82:5)
    at next (node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:82:5)
    at node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (node_modules/express/lib/router/index.js:321:12)
    at next (node_modules/express/lib/router/index.js:261:10)
    at expressInit (node_modules/express/lib/middleware/init.js:23:5)
    at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (node_modules/express/lib/router/index.js:302:13)
    at node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (node_modules/express/lib/router/index.js:321:12)
    at next (node_modules/express/lib/router/index.js:261:10)
    at query (node_modules/express/lib/middleware/query.js:28:5)
    at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:82:5)

I was trying to pay after my colleague in my company could not make the payment either because of an error.

**Comment by NicoleRauch** [comment]
Hi Cyrille,

thanks for the bug report! Can you please tell me which URL you used to do the payment?

Thanks,
Nicole

**Comment by leider** [comment]
Please try again and close this bug eventually. @NicoleRauch fixed it.

**Comment by cyriux** [comment]
Thanks a lot, it now works and I'm now registered for Socrates 2015! Yippee! (it was through https://www.socrates-conference.de/payment)
