### ISSUE TITLE
Login mit StackExchange funktioniert nicht mehr

### ISSUE THREAD

**Issue by NicoleRauch** [softwerkskammer/Agora#984]
Error: Authentication failed (expired token).
    at createUserObject (socrates/lib/authentication/index.js:30:23)
    at module.exports (socrates/lib/authentication/index.js:42:3)
    at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:82:5)
    at next (node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:82:5)
    at node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (node_modules/express/lib/router/index.js:321:12)
    at next (node_modules/express/lib/router/index.js:261:10)
    at expressInit (node_modules/express/lib/middleware/init.js:23:5)
    at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (node_modules/express/lib/router/index.js:302:13)
    at node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (node_modules/express/lib/router/index.js:321:12)
    at next (node_modules/express/lib/router/index.js:261:10)
    at query (node_modules/express/lib/middleware/query.js:28:5)

**Comment by leider** [comment]
maybe on your machine only?
